config/routes.rb
Rails.application.routes.draw do
  resources :reports
  get 'reports/:id/export', to: 'reports#export', as: 'export_report'

  resources :tray_types do
    member do
      post 'activation'
    end
  end

  resources :dispositions do
    member do
      post 'activation'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get 'trays/shelves', to: 'trays#index', as: 'trays'
  post 'trays/shelves', to: 'trays#scan', as: 'scan_tray'
  get 'trays/shelves/:id', to: 'trays#show', as: 'show_tray'
  post 'trays/shelves/:id', to: 'trays#associate', as: 'associate_tray'
  post 'trays/shelves/:id/dissociate', to: 'trays#dissociate', as: 'dissociate_tray'
  post 'trays/shelves/:id/shelve', to: 'trays#shelve', as: 'shelve_tray'
  post 'trays/shelves/:id/unshelve', to: 'trays#unshelve', as: 'unshelve_tray'
  get 'trays/shelves/:id/wrong_shelf', to: 'trays#wrong_shelf', as: 'wrong_shelf'
  get 'trays/shelves/:id/wrong_tray/:barcode', to: 'trays#wrong_tray', as: 'wrong_tray'

  get 'trays/items', to: 'trays#items', as: 'trays_items'
  post 'trays/items', to: 'trays#scan_item', as: 'scan_tray_item'
  get 'trays/items/:id', to: 'trays#show_item', as: 'show_tray_item'
  get 'trays/detail/:barcode', to: 'trays#tray_detail', as: 'tray_detail'
  post 'trays/items/:id', to: 'trays#associate_item', as: 'associate_tray_item'
  post 'trays/items/:id/dissociate', to: 'trays#dissociate_item', as: 'dissociate_tray_item'
  get 'trays/items/:id/missing', to: 'trays#missing', as: 'missing_tray_item'
  get 'trays/items/:id/invalid', to: 'trays#invalid', as: 'invalid_tray_item'
  post 'trays/items/:id/create', to: 'trays#create_item', as: 'create_tray_item'
  get 'trays/items/:id/count_items', to: 'trays#count_items', as: 'count_tray_item'
  post 'trays/items/:id/count_items', to: 'trays#count_items', as: 'validate_count_tray'

  get 'trays/check_items', to: 'trays#check_items_new', as: 'check_items_new'
  post 'trays/check_items', to: 'trays#check_items_find', as: 'check_items_find'
  get 'trays/check_items/:barcode', to: 'trays#check_items', as: 'check_items'
  post 'trays/check_items/:barcode', to: 'trays#validate_items', as: 'check_items_validate'

  post 'trays/:id/withdraw', to: 'trays#withdraw', as: 'withdraw_tray'

  get 'shelves/items', to: 'shelves#index', as: 'shelves'
  post 'shelves/items', to: 'shelves#scan', as: 'scan_shelf'
  get 'shelves/items/:id', to: 'shelves#show', as: 'show_shelf'
  get 'shelves/detail/:barcode', to: 'shelves#shelf_detail', as: 'shelf_detail'
  post 'shelves/items/:id', to: 'shelves#associate', as: 'associate_shelf_item'
  post 'shelves/items/:id/dissociate', to: 'shelves#dissociate', as: 'dissociate_shelf_item'
  get 'shelves/items/:id/wrong/:barcode', to: 'shelves#wrong', as: 'wrong_shelf_item'
  get 'shelves/items/:id/missing', to: 'shelves#missing', as: 'missing_shelf_item'

  get 'shelves/check_trays', to: 'shelves#check_trays_new', as: 'check_trays_new'
  post 'shelves/check_trays', to: 'shelves#check_trays_find', as: 'check_trays_find'
  get 'shelves/check_trays/:barcode', to: 'shelves#check_trays', as: 'check_trays'
  post 'shelves/check_trays/:barcode', to: 'shelves#validate_trays', as: 'check_trays_validate'

  get 'items', to: 'items#index', as: 'items'
  get 'items/scan', to: 'items#scan', as: 'scan_item'
  get 'items/issues', to: 'items#issues', as: 'issues'
  post 'items/resolve', to: 'items#resolve', as: 'resolve_issue'
  get 'trays/issues', to: 'trays#issues', as: 'trays_issues'
  post 'trays/resolve', to: 'trays#resolve', as: 'resolve_tray_issue'
  get 'items/:id', to: 'items#show', as: 'show_item'
  get 'items/detail/:barcode', to: 'items#item_detail', as: 'item_detail'
  post 'items/:id/restock', to: 'items#restock', as: 'item_restock'
  get 'items/:id/wrong_restock', to: 'items#wrong_restock', as: 'wrong_restock'
  post 'items/:barcode/refresh', to: 'items#refresh', as: 'item_refresh'

  get 'search', to: 'search#index', as: 'search'

  get 'batches', to: 'batches#index', as: 'batches'
  post 'batches', to: 'batches#create', as: 'create_batch'
  get 'batches/current', to: 'batches#current', as: 'current_batch'
  post 'batches/remove', to: 'batches#remove', as: 'remove_batch_match'
  get 'batches/retrieve', to: 'batches#retrieve', as: 'retrieve_batch'
  post 'batches/item', to: 'batches#item', as: 'item_batch'
  get 'batches/bin', to: 'batches#bin', as: 'bin_batch'
  post 'batches/scan_bin', to: 'batches#scan_bin', as: 'scan_bin_batch'
  get 'batches/finalize', to: 'batches#finalize', as: 'finalize_batch'
  post 'batches/finish', to: 'batches#finish', as: 'finish_batch'

  get 'batches/view/processed', to: 'batches#view_processed', as: 'view_processed_batches'
  get 'batches/view/processed/:id', to: 'batches#view_single_processed', as: 'view_single_processed_batch'

  get 'batches/view/active', to: 'batches#view_active', as: 'view_active_batches'
  get 'batches/view/active/:id', to: 'batches#view_single_active', as: 'view_single_active_batch'
  post 'batches/view/active', to: 'batches#cancel_single_active', as: 'cancel_single_active_batch'

  get 'transfers/view/active', to: 'transfers#view_active', as: 'view_active_transfers'

  resources :transfers, only: %i[new create show] do
    member do
      put :scan_tray, as: 'scan_tray'
      delete :destroy, as: 'destroy'
      resources :trays, controller: 'transfers', only: [:transfer_tray] do
        put :transfer_tray, as: 'transfer'
      end
    end
  end

  get 'bins', to: 'bins#index', as: 'bins'
  get 'bins/:id', to: 'bins#show', as: 'show_bin'
  get 'bins/detail/:barcode', to: 'bins#bin_detail', as: 'bin_detail'
  post 'bins/remove_match', to: 'bins#remove_match', as: 'bin_remove'
  post 'bins/process_match', to: 'bins#process_match', as: 'bin_process'

  get 'reporting', to: 'reporting#index', as: 'reporting'
  get 'reporting/call_report', to: 'reporting#call_report', as: 'call_report'

  get 'users', to: 'users#index', as: 'users'
  put 'users', to: 'users#update', as: 'update_users'
  post 'users', to: 'users#create', as: 'create_users'

  resources :requests, only: [] do
    collection do
      post :sync
    end
    member do
      delete :remove
    end
  end

  get 'deaccessioning', to: 'deaccessioning#index', as: 'deaccessioning'
  post 'deaccessioning/req', to: 'deaccessioning#req', as: 'deaccessioning_req'

  get 'update', to: 'update#index', as: 'update'
  get 'old_update', to: 'update#old', as: 'old_update'
  get 'show_old_update', to: 'update#show_old', as: 'show_old_update'
  get 'show_existing_update', to: 'update#show_existing', as: 'show_existing_update'
  get 'new_update', to: 'update#new', as: 'new_update'
  get 'show_new_update', to: 'update#show_new', as: 'show_new_update'
  get 'merge_update', to: 'update#merge', as: 'merge_update'

  root 'welcome#index'
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  serialize :fields

  validates :name, presence: true
  validates :activity,
            presence: true,
            inclusion: ActivityLog::ACTIONS
  validates :request_status,
            inclusion: Request::STATUSES.keys,
            allow_blank: true
  validates :item_status,
            inclusion: Item::STATUSES.keys,
            allow_blank: true

  before_save :constrain_fields

  FIELDS = {
    'requested' => 'Requested',
    'filled' => 'Filled',
    'pulled' => 'Pulled',
    'source' => 'Source',
    'request_type' => 'Request Type',
    'patron_status' => 'Patron Status',
    'institution' => 'Institution',
    'department' => 'Department',
    'pickup_location' => 'Pickup Location',
    'class' => 'Class',
    'time_to_pull' => 'Time to Pull',
    'time_to_fill' => 'Time to Fill'
  }.freeze

  PRESET_DATE_RANGES = {
    'current_day' => 'Current Day',
    'previous_day' => 'Previous Day',
    'current_week' => 'Current Week',
    'previous_week' => 'Previous Week',
    'current_month' => 'Current Month',
    'previous_month' => 'Previous Month',
    'current_year' => 'Current Year to Date',
    'current_fiscal_year' => 'Current FY to Date'
  }.freeze

  def run
    BuildReport.call(fields, start_date, end_date, preset_date_range, activity, request_status, item_status)
  end

  def constrain_fields
    self.fields = fields.&(Report::FIELDS.keys)
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy export]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all.order(name: :asc)
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    output = @report.run

    @results = output[:results]
    @sql = output[:sql]

    @report.fields << 'activity'
  end

  def export
    output = @report.run

    @results = output[:results]
    @sql = output[:sql]

    @report.fields << 'activity'

    headers['Content-Disposition'] = \
      "attachment; filename=\"#{@report.name}.csv\""
    headers['Content-Type'] ||= 'text/csv'

    render 'export.csv'
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit; end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    preprocess_start_date(params)
    preprocess_end_date(params)

    params.require(:report).permit(:name, :start_date, :end_date, :preset_date_range, :activity, :request_status, :item_status, fields: [])
  end

  def preprocess_start_date(params)
    if params[:report]['start_date(1i)'].present?
      params[:report]['start_date'] = Date.new(
        params[:report]['start_date(1i)'].to_i,
        params[:report]['start_date(2i)'].present? ? params[:report]['start_date(2i)'].to_i : 1,
        params[:report]['start_date(3i)'].present? ? params[:report]['start_date(3i)'].to_i : 1
      ).to_s

      params[:report].delete('start_date(1i)')
      params[:report].delete('start_date(2i)')
      params[:report].delete('start_date(3i)')
    end

    params
  end

  def preprocess_end_date(params)
    if params[:report]['end_date(1i)'].present?
      year = params[:report]['end_date(1i)'].to_i
      month = params[:report]['end_date(2i)'].present? ? params[:report]['end_date(2i)'].to_i : 12
      day = if params[:report]['end_date(3i)'].present? && params[:report]['end_date(3i)'].to_i <= Time.days_in_month(month, year)
              params[:report]['end_date(3i)'].to_i
            else
              Time.days_in_month(month, year)
            end

      params[:report]['end_date'] = Date.new(
        year,
        month,
        day
      ).to_s

      params[:report].delete('end_date(1i)')
      params[:report].delete('end_date(2i)')
      params[:report].delete('end_date(3i)')
    end
    params
  end
end

app/views/reports/_form.html.haml
= form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :fields
    = f.select :fields, options_from_collection_for_select(Report::FIELDS, 'first', 'last', @report.fields), { include_hidden: false }, { multiple: true }
  .field
    = f.label :start_date
    = f.date_select :start_date, { include_blank: true, default: nil, use_short_month: true }
  .field
    = f.label :end_date
    = f.date_select :end_date, { include_blank: true, default: nil, use_short_month: true }
  .field
    = f.label :preset_date_range
    = f.select :preset_date_range, options_from_collection_for_select(Report::PRESET_DATE_RANGES, 'first', 'last', @report.preset_date_range), { include_hidden: false, include_blank: 'Chooose a time period', default: nil }
  .field
    = f.label :activity
    = f.select :activity, options_from_collection_for_select(ActivityLog::ACTIONS, 'to_str', 'titleize', @report.activity), { include_hidden: false }
  .field
    = f.label :request_status
    = f.select :request_status, options_from_collection_for_select(Request::STATUSES, 'first', 'last', @report.request_status), { include_hidden: false, include_blank: true, default: nil }
    .field
    = f.label :item_status
    = f.select :item_status, options_from_collection_for_select(Item::STATUSES, 'first', 'last', @report.item_status), { include_hidden: false, include_blank: true, default: nil }
  .actions
    = f.submit 'Save'
  :javascript
    $('#report_fields').multiSelect();

app/views/reports/_results.html.haml
.results
  %table.table.table-striped.condensed.datatable{ "id" => "results" }
    %thead
      %tr
        - @report.fields.each do |field|
          %th= (field == 'activity') ? @report.activity.to_str.titleize : Report::FIELDS[field]
    %tbody
      - @results.each do |result|
        %tr
          - @report.fields.each do |field|
            %th= result[field]&.gsub('"', '')

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

= link_to 'Show', @report
\|
= link_to 'Back', reports_path

app/views/reports/export.csv.haml
= CSV.generate_line(@report.fields.map { |field| (field == 'activity') ? @report.activity.to_str.titleize : Report::FIELDS[field] }, {:force_quotes=>true}).strip.html_safe
- @results.each do |result|
  - row = []
  - @report.fields.each do |field|
    - row << result[field]&.gsub('"', '')
  = CSV.generate_line(row, {:force_quotes=>true}).strip.html_safe

app/views/reports/index.html.haml
%h1 Listing reports

%table.reports-list
  %thead
    %tr
      %th Name
      %th Fields
      %th Start date
      %th End date
      %th Preset date range
      %th Activity
      %th Request Status
      %th Item Status
      %th
      %th
      %th

  %tbody
    - @reports.each do |report|
      %tr
        %td= report.name
        %td= report.fields
        %td= report.start_date
        %td= report.end_date
        %td= Report::PRESET_DATE_RANGES[report.preset_date_range]
        %td= report.activity
        %td= report.request_status
        %td= report.item_status
        %td= link_to 'Show', report
        %td= link_to 'Edit', edit_report_path(report)
        %td= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Report', new_report_path

app/views/reports/new.html.haml
%h1 New report

= render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @report.name
%p
  %b Fields:
  = @report.fields
%p
  %b Start date:
  = @report.start_date
%p
  %b End date:
  = @report.end_date
%p
  %b Preset date range:
  = Report::PRESET_DATE_RANGES[@report.preset_date_range]
%p
  %b Activity:
  = @report.activity.titleize
%p
  %b Request Status:
  = Request::STATUSES[@report.request_status]
%p
  %b Item Status:
  = Item::STATUSES[@report.item_status]

- if @results.count == 0
  No Results
  %br
- else
  = render 'results'
  = button_to 'Export', export_report_path(:id => @report.id), method: :get, class: 'btn pull-right btn-primary'
%button{ "data-toggle" => "collapse", :href => "#sql" } Show SQL
.collapse#sql
  %p
  = @sql
%br

= link_to 'Edit', edit_report_path(@report)
\|
= link_to 'Back', reports_path
- if @results.count !=0
  :javascript
      $(document).ready(function() {
        window.table = $('#results').DataTable({ "stateSave": true });
      } );